# Generated by Django 3.0.3 on 2020-02-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emai',
            new_name='email',
        ),
    ]
